### ISSUE TITLE
implement isLocal as default

### ISSUE THREAD

**Issue by zrrrzzt** [p1ho/site-validator-cli#48]
v4.0.0 of [html-validator](https://github.com/zrrrzzt/html-validator) added a property called `isLocal`.
This makes the module get the content of the url and post to the validator as `data`
The reason is to support testing localhost without setting up `localtunnel` or `ngrok`.

It should be quite easy to make `site-validator-cli`support isLocal. However it might be a good idea to let this be the default mode. That would make it possible to test localhost without any extra steps.

**Comment by p1ho** [comment]
I agree on this change. I was also thinking about making this possible for localhost as well.

As an example for a use case, this would be very helpful for people using GitHub to host their sites. Because of caching GitHub Pages have a delay between when things are pushed and when the webpages are updated. Consequently passing in GitHub Pages url will not return the latest validation status.

This would complicate a bit the caching mechanism discussed in #47 , because if users switch their localhost server to another project folder, the url is still just `localhost/`, and it would actually get the urls fetched from the last project folder and cause 404's.

**Comment by zrrrzzt** [comment]
Caching might be a challenge indeed.

Maybe it would be better to implement `--isLocal` as a flag instead of default.
In that case you would do an active choice to activate it and we could recommend always using `--clear-cache` together with `--isLocal` in the README

**Comment by p1ho** [comment]
in `html-validator`, if isLocal is set to true, does it take care of fetching the text content?
I think the answer is yes from looking at the doc, but it'd be nice to get a confirmation.

**Comment by zrrrzzt** [comment]
Yes. With `isLocal` request retrieves the page and adds the content to `options.data`https://github.com/zrrrzzt/html-validator/blob/master/lib/config.js#L29
