### ISSUE TITLE
Save verbose output to file

### ISSUE THREAD

**Issue by richiekastl** [p1ho/site-validator-cli#52]
Is there a way to save the verbose output to a file?

**Comment by p1ho** [comment]
in command line you should be able to do something like
```bash
$ site-validator <url> --verbose > output.txt
```
or 
```bash
$ site-validator <url> --verbose | tee output.txt
```
Both of them should save the output to a file `output.txt`, the only difference is console logs are suppressed in the first one.
However, doing this way the colored texts will have special characters around them.
Example:
![image](https://user-images.githubusercontent.com/22629067/59219680-0a400f80-8b91-11e9-9c0e-faeb49921305.png)

I'm all for having a `--log` flag that saves the file to where the command is being run,
but I left it out because I wasn't sure how to best format the logs.
I imagine if the website is large (like 100+ pages), then perhaps a csv/json format output rather than just a simple text dump is more desirable.

If you want, feel free to make a fork and submit a PR!

**Comment by zrrrzzt** [comment]
I think `-- output` or `-o` would be a better flag than `--log`.

Regarding implementation I agree to find a more structured format than coloured text.

**Comment by p1ho** [comment]
I may be overthinking it a little bit, but I think the *Ultimate Solution* would be to output a formatted html file which itself could be used as a report; and if a csv or a json is needed, I could just create links in the html file that would download/generate them.

**Comment by richiekastl** [comment]
> I may be overthinking it a little bit, but I think the Ultimate Solution would be to output a formatted html file which itself could be used as a report; and if a csv or a json is needed, I could just create links in the html file that would download/generate them.

This would be fantastic. It would be so helpful to be able to send a report like this to my team.

**Comment by zrrrzzt** [comment]
I think you overthink it ;-)

If we could build the content of the report in json we could probably generate different types of reports. html could be one format, csv another.

**Comment by p1ho** [comment]
@zrrrzzt I see, maybe we should start simple first. The json output will have enough flexibility for later stuff, but it's the absolute baseline.
@richiekastl I'll focus on creating a json output first, then I can write a separate gist that might be able to help you.

**Comment by p1ho** [comment]
@richiekastl I published the [new update](https://github.com/p1ho/site-validator-cli/pull/53). After updating to the newest version, you'll be able to run command like `$ site-validator <url> --output <filename>` and it will generate a `filename.json` in the directory where the command was executed.

Using that file, you can then download and run [this gist](https://gist.github.com/p1ho/05f418139187ed6de49d15648a9ad826) with node (requires [html-creator](https://www.npmjs.com/package/html-creator) as a dependency), which will generate a html report in the same directory. The report looks ugly atm, but I trust you can make it look a lot more professional than I can.

Hope it helps! I will close when it's confirmed your issue is solved.

**Comment by richiekastl** [comment]
@p1ho Thank you! The output is very helpful. I might even make a little Vue app with it that will let users interact with the data easily (check off no longer relevant issues, sort issues, etc). Not sure if that app would fit into the scope of this repo or not, it could be its own repo that's referenced in this repo's readme.

**Comment by p1ho** [comment]
No problem! I think anything beyond the json output is outside the scope for this project, but I can definitely include your project in the readme once you've released it.
