### ISSUE TITLE
Upcoming changes to html-validator

### ISSUE THREAD

**Issue by zrrrzzt** [p1ho/site-validator-cli#88]
Hi, I'm doing a big update for html-validator at the moment. You can look at the work in this branch: https://github.com/zrrrzzt/html-validator/tree/html-validate

The main change is to use [html-validate](https://www.npmjs.com/package/html-validate) for validation instead of posting to w3c validator. By doing that you can do all validation locally and you can probably gain a significant higher speed for your tests.

However: the reports will look a bit different.

If you look at the branch there is a working implementation of the code and json-report. I will update the documentation and create a text-report this weekend.

It will be a breaking change so you are properly warned before merging :-)

**Comment by p1ho** [comment]
Absolutely, thanks for letting me know!

**Comment by p1ho** [comment]
I was looking at [the discussion on moving to html-validate](https://github.com/zrrrzzt/html-validator/issues/162).

I'm still debating on whether I want to make the change; since part of this package's purpose is that users don't have to enter their html files one by one on the official w3c validator.

(I could probably pin the version of html-validator if I don't end up migrating with it)

**Comment by zrrrzzt** [comment]
Yes, the latest development is that it will probably support both W3C and html-validate.
In that case you can opt in support when you have the time.

**Comment by p1ho** [comment]
@zrrrzzt Hello, so I just read the new updates, it looks like the new changes will not override the default behavior. Does this mean I don't need to make any code change if I'm just using the official w3c validator? Thanks!

**Comment by zrrrzzt** [comment]
Yes, that would be correct :-)

I'll close this issue.
